kolonDT/202205_wecode_fr

- src/App.js
- src/Pages/Complete/CompleteForm.js
<br />
1. 등록완료 페이지 구현
2. 요청 내역 클릭 시 요청내역으로 이동하도록 기능추가
3. 알람설정, 알람해제 클릭 시 toast메시지 출력하도록 기능 추가
-
> ADD: 등록완료 페이지 구현 

- src/App.js
- src/Pages/Sellcar/InfoForm1.js
- yarn.lock
<br />
1. 버튼을 누르면 사진 업로드 가능
2. 업로드한 사진 미리보기 가능
- 디자인 미완성
- 사진 올리기 전 레이아웃 필요
> ADD: 사진 업로드 기능 완성

- package-lock.json
- package.json
- src/App.js
- src/Components/Modal/WarningModal.js
- src/Pages/Sellcar/ContactInfo.js
- src/Pages/Sellcar/InfoForm1.js
- src/Pages/Sellcar/MapInfo.js
- src/Pages/Sellcar/Sellcar.js
<br />
1.추가정보-연락처,지역찾기  기능 추가
-
> ADD: 추가정보-연락처,지역찾기  기능 추가

- src/Pages/Sellcar/InfoForm1.js
<br />
1. 업로드 된 이미지 크기 및 위치를 조정했습니다.
-
> ADD : 이미지 업로드 디자인 추가

- package.json
> ADD: https설정 추가

- src/App.js
- src/Pages/Login/Login.js
- src/Pages/Sellcar/Reconfirm.js
- yarn.lock
<br />
견적신청 완료페이지 레이아웃 작업 완성
-
> 견적신청 완료 페이지 레이아웃 작업완성

- public/Data/Hani/adminData.json
- src/App.js
- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarCard.js
<br />
1. 관리자 페이지에서 모든 견적 차량의 요청 내역을 관리할 수 있게 구현
2. 견적 차량의 정보가 카드 형식으로 나열 되어 있고 클릭할 수 있다.
3. 클릭 시 요청 내역을 관리할 수 있는 체크박스가 나온다.
4. 체크박스를 클릭 시 해당 과정을 DB에 전달한다. 
-
> ADD : 관리자 페이지

- Dockerfile
- package-lock.json
- yarn.lock
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> action 오류 해결작업

- src/Pages/Sellcar/InfoForm1.js
<br />
1. 사진을 4개 이상 업로드하면 알럿창이 뜨고 더이상 추가할 수 없게 만든다.
2. 사진에 마우스를 호버하면 삭제 버튼이 뜨고 클릭하면 업로드된 사진이 삭제된다.
-
> ADD: 사진 업로드 제한 기능 및 삭제 기능 추가

- src/Pages/Admin/CarCard.js
<br />
1. 기존에 진행되던 견적 요청 단계도 체크박스에 반영하게 구현했습니다.
2. 순서대로 체크할 수 있도록 기능을 추가했습니다.
-
> ADD: 견적 내용 관리 기능 추가

- src/Pages/Sellcar/InfoForm1.js
<br />
1. 로컬스토리지에 값이 없으면 에러가 생겨서 렌더링 문제가 있었습니다.
2. 조건문을 두어 로컬스토리지에 값이 있으면 실행할 수 있게 수정했습니다.
-
> FIX: sellcar 렌더링 에러 해결

- package-lock.json
- package.json
- src/Components/Header.js
- src/Pages/Complete/CompleteForm.js
- src/Pages/Requestform/RequestForm.js
- src/Pages/Sellcar/ContactInfo.js
- src/Pages/Sellcar/MapInfo.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> ADD: localstorage에 저장되도록 기능 추가

- src/Components/Modal/WarningModal.js
- src/Pages/Sellcar/Sellcar.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> ADD: 견적 받기 버튼 기능 구현

- src/Pages/Sellcar/AddInfo.js
- src/Pages/Sellcar/ContactInfo.js
- src/Pages/Sellcar/InfoForm1.js
- src/Pages/Sellcar/Sellcar.js
- yarn.lock
> FIX: Feature/sellcar

- src/Pages/Login/LoginMain.js
- src/Pages/Sellcar/Graph.js
- src/Pages/Sellcar/Sellcar.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: 메인페이지 스타일 수정작업중..

- package.json
- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarCard.js
> ADD: FETCH 주소

- package.json
- src/Pages/Admin/CarCard.js
<br />
1. 요청 내역 업데이트 fetch 코드를 수정했습니다.
- METHOD -> PATCH로 수정
- body에 보내는 내용 JSON.stringify 사용
> FIX: fetch 코드 수정 

- package.json
- src/Pages/Login/LoginMain.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> ADD: 로컬스토리지에 carNumber 넣기작업

- src/App.js
- src/Components/Header.js
- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarCard.js
- src/Pages/Complete/CompleteForm.js
- src/Pages/Requestform/RequestForm.js
- src/Pages/Sellcar/ContactInfo.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: backend와 연동으로 인한 코드 수정

- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarCard.js
- src/Pages/Complete/CompleteForm.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX : alarm설정시 두번 수정되는 문제 수정

- src/Pages/Requestform/RequestForm.js
- src/Pages/Sellcar/Sellcar.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: 반응형에 맞게 몇가지 수정

- src/App.js
- src/Pages/Login/LoginMain.js
- src/Pages/Sellcar/Graph.js
<br />
1. 컴포넌트를 활성화 시 props로 setPage 함수를 전달해주지 않았던 에러를 잡고 수정했습니다.
-
> FIX: sellcar 컴포넌트 활성화 시  setPage 오류 수정

- src/Pages/Complete/CompleteForm.js
- src/Pages/Login/Login.js
- src/Pages/Requestform/RequestForm.js
- src/Pages/Sellcar/AddInfo.js
- src/Pages/Sellcar/ContactInfo.js
- src/Pages/Sellcar/MapInfo.js
- src/Pages/Sellcar/Reconfirm.js
- src/Pages/Sellcar/Sellcar.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: localStorage 로직 변경

- src/Pages/Complete/CompleteForm.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: 글자크기 변경

- package.json
- src/Pages/Admin/CarCard.js
<br />
1. CarCard에서 요청 내역 업데이트 fetch api url 수정
-
> FIX: 요청 내역 업데이트 Fetch URL 수정

- src/Pages/Login/Login.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> ADD : DB에 존재하는 차량의 경우 조회하기 기능 추가

- package.json
- src/App.js
- src/Components/Header.js
- src/Pages/Login/Login.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: header 알림관련 버그 수정

- src/Components/Header.js
- src/Pages/Admin/CarCard.js
- src/Pages/Api/Api.js
- src/Pages/Complete/CompleteForm.js
- src/Pages/Login/Login.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 코드 정리
2. 변경된 기획사항 반영
-
> FIX: 코드 리팩토링 및 변경된 기획사항 반영

- src/Pages/Login/Login.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX :코드 리팩토링

- src/Components/Graph/DummyData.js
- src/Components/Graph/Graph.js
<br />
- 그래프에 내 차 지점 표시
- 더미데이터 넣어 라인차트 만들기 작업
-
> ADD: 그래프에 내 차 지점 표시 및 더미데이터 넣어 라인차트 만들기 작업

- src/Components/Graph/Graph.js
- src/Pages/Sellcar/Reconfirm.js
<br />
- 차량 사진 slick라이브러리 사용으로 슬라이드 형식으로 보여주기 작업 진행중
-
> ADD: 견적 완료페이지 등록차량 사진 slick라이브러리 적용

- package.json
- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarLine.js
- yarn.lock
<br />
1. DB랑 연결할 수 있도록 API 코드를 수정했습니다.
-
> FIX: API 연결

- src/Pages/Requestform/RequestForm.js
- src/Pages/Sellcar/Sellcar.js
<br />
1. AddInfo 컴포넌트 중복 버그 해결
-
> FIX: sellcar 컴포넌트 중복 버그 수정

- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarLine.js
- src/Pages/Api/Api.js
- src/Pages/Complete/CompleteForm.js
- src/Pages/Login/Login.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> refactoring

- package.json
- src/Pages/Admin/CarLine.js
- src/Pages/Api/Api.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> ADD: 수정된 admin페이지에 맞춰 알림기능 추가

- src/App.js
- src/Components/Footer.js
- src/Components/Header.js
- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarLine.js
- src/Pages/Admin/Pagination.js
- src/Pages/Sellcar/AddInfo.js
- src/Pages/Sellcar/PhotoCard.js
- src/Pages/Sellcar/Reconfirm.js
<br />
1. 관리자 페이지 레이아웃 변경
2. 썸네일 디자인 변경
-
> ADD: 관리자 페이지 레이아웃 변경 및 썸네일 디자인 변경

- package.json
- src/Pages/Api/Api.js
- src/Pages/Complete/CompleteForm.js
- src/Pages/Requestform/RequestForm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: fetch경로 수정

- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarLine.js
- src/Pages/Sellcar/AddInfo.js
- src/Pages/Sellcar/PhotoCard.js
- src/Pages/Sellcar/Sellcar.js
<br />
1. 업로드한 이미지 수정 기능
2. 업로드한 이미지 삭제 기능
3. 사진 업로드 반응형 구현
4. 관리자 페이지 페이지네이션 버그 해결
5. 관리자 페이지 삭제 리렌더링 버그 해결
-
> FIX: 이미지 업로드 및 관리자 페이지 수정

- src/Pages/Login/Login.js
- src/Pages/Requestform/RequestForm.js
- src/Pages/Sellcar/ContactInfo.js
- src/Pages/Sellcar/MapInfo.js
- yarn.lock
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX : bug 및 css 스타일 수정

- src/Pages/Admin/CarLine.js
- src/Pages/Sellcar/PhotoCard.js
- src/Pages/Sellcar/Reconfirm.js
- src/Pages/Sellcar/Sellcar.js
<br />
1. 업로드 한 사진이 DB에 저장되지 않는 버그를 수정했습니다.
-
> FIX : 사진 업로드 버그 수정

- Dockerfile
- package.json
- src/Pages/Admin/Admin.js
- src/Pages/Admin/CarLine.js
- src/Pages/Api/Api.js
- src/Pages/Graph/Graph.js
- src/Pages/Login/Login.js
- src/Pages/Login/LoginMain.js
- src/Pages/Requestform/RequestForm.js
- src/Pages/Sellcar/Reconfirm.js
- src/config.js
- src/index.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX : config파일로 변수 관리하도록 수정

- src/Pages/Requestform/RequestForm.js
- src/config.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: config 수정

- src/Pages/Graph/Graph.js
- src/Pages/Sellcar/Reconfirm.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: 시세그래프 api연동 작업

- src/Pages/Login/Login.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: login 로직 수정

- src/Pages/Sellcar/MapInfo.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX:map 로직 수정

- src/Pages/Sellcar/MapInfo.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> Develop to main

- src/Pages/Sellcar/MapInfo.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: 예외처리 추가

- src/config.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: bug fix

- src/Pages/Sellcar/MapInfo.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX: 위도 경도 값이 null일때 예외처리 추가

- src/Pages/Sellcar/MapInfo.js
<br />
1. 구현사항 기록
2. 구현사항 기록
-
> FIX : geolocation api가 작동하지 않을시 예외처리 추가
